version: '3'


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: my_homepage_local_django
    container_name: django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  docs:
    image: my_homepage_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./my_homepage:/app/my_homepage:z
    ports:
      - "7000:7000"
    command: /start-docs

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *django
    image: my_homepage_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - django
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: my_homepage_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - django
    ports: []
    command: /start-celerybeat
