# Generated by Django 3.1.11 on 2021-05-24 19:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(editable=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('tags', models.ManyToManyField(related_name='posts', to='posts.Tag')),
            ],
        ),
    ]
