# Generated by Django 3.1.11 on 2021-05-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
