# Generated by Django 3.1.11 on 2021-05-25 01:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_auto_20210524_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=tinymce.models.HTMLField(),
        ),
    ]
