# Generated by Django 3.1.11 on 2021-05-27 15:19

from django.db import migrations, models
import phone_field.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_auto_20210525_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=tinymce.models.HTMLField(help_text='Everything about yourself'),
        ),
        migrations.AlterField(
            model_name='about',
            name='github_link',
            field=models.URLField(blank=True, help_text='Link to your GitHub profile'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(help_text='First and last name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='pic',
            field=models.ImageField(default='default-img.jpg', help_text='Profile picture', upload_to='pics'),
        ),
    ]
