# Generated by Django 3.1.11 on 2021-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0005_auto_20210527_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
