# Generated by Django 3.1.11 on 2021-05-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0006_about_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
    ]
