# Generated by Django 3.1.11 on 2021-05-24 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Name of the skill', max_length=50)),
                ('years_experience', models.IntegerField(help_text='Years experience with skill')),
                ('notes', models.CharField(help_text='Anything extra worth annotating', max_length=250)),
            ],
        ),
    ]
