# Generated by Django 3.1.11 on 2021-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('OTHER', 'Other')], default='OTHER', help_text='Category for the skill', max_length=8),
        ),
    ]
