# Generated by Django 3.1.11 on 2021-05-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='notes',
            field=models.CharField(default='', help_text='Anything extra worth annotating', max_length=250),
        ),
    ]
