# Generated by Django 3.1.11 on 2021-05-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_auto_20210524_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='notes',
            field=models.CharField(default=' ', help_text='Anything extra worth annotating', max_length=250),
        ),
    ]
