# Generated by Django 3.1.11 on 2021-05-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20210524_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Anything extra worth annotating', max_length=250),
        ),
    ]
