# Generated by Django 3.1.11 on 2021-05-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_auto_20210524_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.CharField(max_length=250)),
            ],
        ),
    ]
