# Generated by Django 3.1.11 on 2021-05-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_skillsoverview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillsoverview',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Skills Overview'},
        ),
    ]
