# Generated by Django 3.1.11 on 2021-06-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_auto_20210528_1401'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'category')},
        ),
    ]
