# Generated by Django 3.1.11 on 2021-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_auto_20210601_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsoverview',
            name='overview',
            field=models.CharField(help_text='Overview of skills', max_length=250),
        ),
    ]
