# Generated by Django 3.1.11 on 2021-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcontact',
            name='content',
            field=models.CharField(help_text='Contact content', max_length=5000),
        ),
        migrations.AlterField(
            model_name='newcontact',
            name='email',
            field=models.EmailField(help_text='Contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='newcontact',
            name='name',
            field=models.CharField(help_text='Contact name', max_length=60),
        ),
        migrations.AlterField(
            model_name='newcontact',
            name='subject',
            field=models.CharField(blank=True, help_text='Contact subject', max_length=150),
        ),
    ]
